import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import style from './layout.module.css'
import '@radix-ui/themes/tokens/base.css';

// Include just the colors you use, for example `ruby`, `teal`, and `slate`.
// Remember to import the gray tint that matches your theme setting.
import '@radix-ui/themes/tokens/colors/red.css';
import '@radix-ui/themes/tokens/colors/gray.css';
import '@radix-ui/themes/tokens/colors/green.css';
import '@radix-ui/themes/tokens/colors/indigo.css';
import '@radix-ui/themes/tokens/colors/slate.css';

// Rest of the CSS
import '@radix-ui/themes/components.css';
import '@radix-ui/themes/utilities.css';

import { Box, Grid, Theme, } from '@radix-ui/themes';
import Sidebar from "./components/sidebar";
import Header from "./components/header";
import { ThemeProvider } from "@/app/components/theme-provider";
import { SidebarContext } from "./components/SidebarContext";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"], });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning={true}  className={inter.className + ""}>
        <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
        >
          <Theme>
            <div>
              <div className={style.Main_Container}>
                <Grid gap="0" columns={{ initial: '1', md: '15% 85%', lg: '15% 85%', sm: "0% 100%", xs: "0% 100%" }} rows="repeat(1, 1fr)" flow="row" width="100%">
                  <Box>
                    <Sidebar></Sidebar>
                  </Box>
                  <div className="main-content">
                    <Header></Header>
                    {children}
                  </div>
                </Grid>
              </div>
            </div>
          </Theme>
        </ThemeProvider>
      </body>
    </html>
  );
}
